### ISSUE TITLE
Session value example

### ISSUE THREAD

**Issue by stanonyime** [chentsulin/koa-graphql#10]
In the express-graphql repo, there is an example in the Readme demonstrating session usage. How will that look like with koa-graphql? Basically, I want to access session variables and use it in my schema

**Comment by santialbo** [comment]
this library needs to expose the koa context on the options function, not just the original node request.

**Comment by chentsulin** [comment]
It's undocumented, but this lib already expose the koa context on the options function now.
https://github.com/chentsulin/koa-graphql/blob/master/src/index.js#L188

**Comment by chentsulin** [comment]
Example added. See https://github.com/chentsulin/koa-graphql/pull/22/files

**Comment by prewk** [comment]
Have I understood correctly that this:

````js
app.use(mount('/api', graphqlHTTP((request, context) => ({
    schema: Schema,
    context: { foo: 'bar' },
}))));
````

...should make argument 3 on my schema's `resolve` equal `{ foo: 'bar' }`? I currently get a schema object there instead, what am I missing? (Some fundamental fact about the graphql resolve methods "context" I assume)

````js
{
  fieldName: 'viewer',
    fieldASTs: [ ... ],
    returnType: ....,
    parentType: ....,
    schema: ...,
    ...etc...
}
````

Thanks!

**Comment by chentsulin** [comment]
`context` only be supported after `v0.5.0`. You may use the old version of koa-graphql (< 0.5) and graphql (< 0.5). Here is the resolve's 3rd argument example before 0.5.0:

```js
new GraphQLObjectType({
  name: 'MyType',
  fields: {
    myField: {
      type: GraphQLString,
      resolve(parentValue, _, { rootValue }) {
        //
      }
    }
  }
});
```

**Comment by prewk** [comment]
Ah, that explains it! I used the old version due to some conflicting peerDeps, but I'll sort em out and try the newer version. Thanks.

**Comment by prewk** [comment]
..since I'm still deep in peerDep problems (I think it's because `isomorphic-relay` hasn't upgraded yet), did I understand you correctly that there is no sensible way of getting the context data in 0.4?

**Comment by chentsulin** [comment]
You can achieve your goal using `rootValue` in 0.4. Please checkout old README here:
https://github.com/chentsulin/koa-graphql/tree/v0.4.13#advanced-options

**Comment by Blackening999** [comment]
More info here:
https://github.com/Secbone/koa-session2/issues/46
