### ISSUE TITLE
GraphQL v14 support

### ISSUE THREAD

**Issue by lukeshiru** [chentsulin/koa-graphql#117]
Right now `koa-graphql` supports an old version of graphql (0.13.2), but the latest one is v14.0.2. This should be fixed because GraphQL doesn't support to have multiple instances installed.

If you need any help with this update I could try to make a PR for it 👍

**Comment by chentsulin** [comment]
We now have v14 support in 0.8.0
https://github.com/chentsulin/koa-graphql/releases/tag/v0.8.0
