### ISSUE TITLE
More specific handle (req, request) and (res, response) 

### ISSUE THREAD

**Issue by chentsulin** [chentsulin/koa-graphql#2]
It's helpful for using node `req` and node `res` to directly migrate from express to koa, but It's not the koa style. We should use `request` and `response` wrapped by koa.

**Comment by burkhardr** [comment]
Agreed. Stumbled across that when using `graphql-koa` which seemed to confuse the two (probably just a straight copy-pasta from `express-graphql`.

**Comment by LorbusChris** [comment]
+1 to this. Maybe someone could get the extended config examples from the original express-graphql repo as well. Do you plan to keep this repo here updated?

**Comment by chentsulin** [comment]
Sure. We will try to follow express-graphql repo, besides the point which koa can do something better than express. Any PRs are also welcome.

**Comment by chentsulin** [comment]
For now, we don't expose any req and res stuff in our public api, so I am going to close this issue.
