### ISSUE TITLE
how to using koa-graphql with koa-router@7.0.0

### ISSUE THREAD

**Issue by m927259903** [chentsulin/koa-graphql#27]
i used koa-router and koa-graphql with koa2 like this:
```js
var router = new Router();
router.use('/graphql',graphqlHTTP({schema: schema}));
app.use(router.routes());
```
when i visite `/graphql`. but the router not work.
how do i do. thx.

**Comment by chentsulin** [comment]
Would `koa-covert` help?

```js
var convert = require('koa-convert');
var router = new Router();
router.use('/graphql', convert(graphqlHTTP({schema: schema})));
app.use(router.routes());
```

**Comment by m927259903** [comment]
yes  i tried , but it didn't work

**Comment by mattecapu** [comment]
`koa-convert` worked for me.

**Comment by m927259903** [comment]
okay. let me try

**Comment by chentsulin** [comment]
`koa-convert` should works, all tests passed on next branch https://github.com/chentsulin/koa-graphql/tree/next

**Comment by thewillhuang** [comment]
var router = new Router();
router.all('/graphql',graphqlHTTP({schema: schema}));
app.use(router.routes());

use `all` instead of `use` for router
