### ISSUE TITLE
Unmet peer dependency graphql

### ISSUE THREAD

**Issue by felixsanz** [chentsulin/koa-graphql#37]
As said in self-closed #32:

 npm install --save koa-graphql
universal-js@0.0.1 .../Desktop/app
├── UNMET PEER DEPENDENCY babel-eslint@6.0.0
├── UNMET PEER DEPENDENCY graphql@^0.4.16
└─┬ koa-graphql@0.4.13 
  └─┬ raw-body@2.1.6 
    ├── bytes@2.3.0 
    └── iconv-lite@0.4.13 

Execution:

```
module.js:341
    throw err;
    ^

Error: Cannot find module 'graphql'
```

**Comment by chentsulin** [comment]
You should install graphql as well:

npm install --save graphql

perrDeependencies will not be auto installed when using npm@3
