### ISSUE TITLE
Q: Thoughts on debugging tools?

### ISSUE THREAD

**Issue by amccloud** [chentsulin/koa-graphql#6]
It would be great if we could pass an option that logs the request query and variables and the response data. Does that belong in this library or should I create like koa-graphql-logging?

**Comment by chentsulin** [comment]
`koa-graphql-logging` sounds great. Middlewares come into play in this situation, and other debugging tools or filters are the same.

**Comment by chentsulin** [comment]
If you have completed your work on it, I can mention it in this repo's README

**Comment by sibelius** [comment]
@amccloud any progress on koa-graphql-logging?

**Comment by amccloud** [comment]
@sibelius I didn't end up working on it.

**Comment by rturk** [comment]
This is a big miss for me. I have no ideia of what is happening on the sever.
