### ISSUE TITLE
How to yield in a resolver?

### ISSUE THREAD

**Issue by pyros2097** [chentsulin/koa-graphql#60]
I'm trying to use the generator in the resolver of a graphql type? But it doesn't seem to work.
```js
new GraphQLObjectType({
  name: 'MyType',
  fields: {
    myField: {
      type: GraphQLString,
      resolve: function *(parentValue, args, session) {
          return yield fetch("/some/api")
      }
    }
  }
});
```
The returned value is this
```
{
  "myField": ["Object generator"]
}
```
I guess its not possible to make resolvers synchronous using yields.

**Comment by pyros2097** [comment]
I checked it out from this lib and they do a yield on the graphql execute function so I think even you need to be doing that...
https://github.com/RisingStack/graffiti/blob/master/src/koa/koa.js

**Comment by chentsulin** [comment]
`GraphQLObjectType` is a constructor come from `graphql.js`:
https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L318

So there is nothing we can do here.

Not that you can return a promise directly in your resolve function:

```js
new GraphQLObjectType({
  name: 'MyType',
  fields: {
    myField: {
      type: GraphQLString,
      resolve: function (parentValue, args, session) {
          return fetch("/some/api")
              .then(res => res.json())
              .then(json => json.myKey);
      }
    }
  }
});
```

Or use `co` library:

```js
new GraphQLObjectType({
  name: 'MyType',
  fields: {
    myField: {
      type: GraphQLString,
      resolve: function (parentValue, args, session) {
          return co(function *() {
              const res = yield fetch("/some/api");
              const json = yield res.json();
              return json.myKey;
          });
      }
    }
  }
});
```

**Comment by pyros2097** [comment]
Yeah this is what i figured .. anyways time to implement IOC ftw.
