### ISSUE TITLE
Exposing graphql request?

### ISSUE THREAD

**Issue by pyros2097** [chentsulin/koa-graphql#64]
I know that you can access the request object when you initiate the middleware but is it possible for me to get the graphql request's info also so that I can log it,
example:

``` js
graphqlHTTP((request, context) => {
       console.log(request.graphqlQuery);
       console.log(request.graphqlVariables);
})
```

Right now when I make a post request, I don't know what requests are hitting my server?

**Comment by chentsulin** [comment]
This is impossible at this moment. Open a new issue at express-graphql: https://github.com/graphql/express-graphql/issues/113

Relative issue: #6

**Comment by sibelius** [comment]
@pyros2097 have u figure it out how to do this?

@chentsulin is there any workaround for now? like logging POST data

**Comment by pyros2097** [comment]
Nope... I thought of doing a fork but then lost interest since it gets cumbersome to maintain it and add it as a dependency.

**Comment by chentsulin** [comment]
@sibelius Sorry, but there is no workaround for this now. I can add a custom logger here: https://github.com/chentsulin/koa-graphql/blob/master/src/index.js#L159, but I rather waiting for @leebyron 's feedback in https://github.com/graphql/express-graphql/issues/113 .

**Comment by chentsulin** [comment]
@sibelius @pyros2097 #79 introduce a new point to extend, will this help you?

**Comment by pyros2097** [comment]
Yep!

**Comment by sibelius** [comment]
tks
