### ISSUE TITLE
install from github

### ISSUE THREAD

**Issue by sibelius** [chentsulin/koa-graphql#66]
is it possible to install koa-graphql directly from github?

`npm i git+ssh://git@github.com/chentsulin/koa-graphql.git --save`

the folder of koa-graphql it is empty inside node_modules when I install from github

**Comment by marvinhagemeister** [comment]
Can confirm this. NPM only pulls `LICENSE`,  `PATENTS`, `README` and `package.json`. The src and resources folder are both missing.

**Comment by chentsulin** [comment]
You need to clone, build locally, then install from the local path.
Reference: https://github.com/reactjs/react-router/pull/3164

**Comment by marvinhagemeister** [comment]
@chentsulin Thanks for the heads-up. That clears things up 🎉
