### ISSUE TITLE
Expose GetBody Limits?

### ISSUE THREAD

**Issue by pyros2097** [chentsulin/koa-graphql#68]
Allow limit to be passed instead of forcing it to 100Kb. Just got an error in production while doing a demo and flipped. At least set the default to something like 1mb or 2mb.

**Comment by chentsulin** [comment]
There are some discuss at the upstream repo: https://github.com/graphql/express-graphql/pull/72

**Comment by mcrawshaw** [comment]
Would you accept a PR on this?  Move the default to 1mb + add a new option "bodyLimit" to the API.  Either or both.

**Comment by chentsulin** [comment]
I plan to complete #75 in next release, so I am afraid this is not I can help here. For future, we may move to decoupled middlewares see: https://github.com/graphql/express-graphql/pull/72#issuecomment-258039863

**Comment by chentsulin** [comment]
getBody is gone after #76 merged, so may move to https://github.com/graphql/express-graphql/pull/72

**Comment by mcrawshaw** [comment]
Roger, no problems.
