### ISSUE TITLE
Support HEAD method for /graphql

### ISSUE THREAD

**Issue by rturk** [chentsulin/koa-graphql#69]
I have multiple instances of GraphQL servers running behind a AWS ELB (elastic load balancer). 

ELB recurrently checks the status of each node performing a small ping to each node.  AWS default validation mode uses `HEAD` method (it will not use GET or POST). 

Currently (as far I was able to check) koa-graphql will return a error if a `HEAD` request is performed. This causes ELB to assume that the node is dead and will stop to route requests.

Need `HEAD` to also be supported

**Comment by rturk** [comment]
If I run:
`curl -X HEAD http://localhost:5000/graphql -I
`

I'll get the following response:

```
HTTP/1.1 405 Method Not Allowed
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET,HEAD,PUT,POST,DELETE
Allow: GET, POST
Content-Type: application/json; charset=utf-8
Content-Length: 1482
Date: Tue, 04 Oct 2016 16:55:17 GMT
Connection: keep-alive
```

**Comment by thewillhuang** [comment]
this does not quite make sense, it should not be the responbility of the package to make routes for you. Why don't you just do 
```js
const koa = require('koa');
const Router = require('koa-router'); // koa-router@7.x
const convert = require('koa-convert');
const graphqlHTTP = require('koa-graphql');

const app = new Koa();
const router = new Router();
const graphql = convert(graphqlHTTP((request, ctx) => {
  ...
}));

router
  .head('/graphql', (ctx, next) => ctx.status = 200)
  .get('/graphql', graphql)
  .post('/graphql', graphql)

app.use(router.routes()).use(router.allowedMethods());
```

**Comment by chentsulin** [comment]
Thanks for @thewillhuang 's tip! 

There are a lot of ways to get this to be done by router and your middlewares, so just feel free to handle `head` request on your side.
