### ISSUE TITLE
Input Data of a Mutation are not based on Standard JavaScript Object/ Array

### ISSUE THREAD

**Issue by vanthome** [chentsulin/koa-graphql#89]
If I have a mutation like this:

```js
import { mutationWithClientMutationId } from 'graphql-relay';
export default mutationWithClientMutationId({
  name: 'BulkImportOrganizations',
  inputFields: {
    listOfOrganizations: {
      type: new GraphQLList(OrganizationType),
    },
    apiKey: {
      type: GraphQLString,
    },
  },
  mutateAndGetPayload: async({ listOfOrganizations, apiKey }) => {
    const output = {
      regStatus: [],
      error: {
        code: [],
        message: []
      }
    };
```
I wounder why is **listOfOrganizations** not an array? It seems to be a pseudo array but does not implement the corresponding methods according to the [Array Prototype](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/prototype?v=example) neither it has the Array prototype. The same goes for plain Objects.

**Comment by chentsulin** [comment]
If I’m not mistaken, this should not be an issue about `koa-graphql`.

**Comment by vanthome** [comment]
ok but what else?

**Comment by chentsulin** [comment]
All of GraphQL queries are executed directly by [GraphQL-js](https://github.com/graphql/graphql-js), so if you have any questions about that you should go to see the implement there.

https://github.com/chentsulin/koa-graphql/blob/1ff01ea269d665dae5020593bb7a458611f4f35d/src/index.js#L257-L263
