### ISSUE TITLE
GraphiQL version error

### ISSUE THREAD

**Issue by F-happy** [chentsulin/koa-graphql#94]
<img width="1001" alt="dingtalk20170727183014" src="https://user-images.githubusercontent.com/8241236/28666381-a8fbf2ea-72f9-11e7-8016-fa9c3afb8185.png">

### in code
GRAPHIQL_VERSION = '0.10.1'
 
### should
GRAPHIQL_VERSION = '0.10.2' or latest

**Comment by chentsulin** [comment]
Updated to `v0.11.2`:

https://github.com/chentsulin/koa-graphql/releases/tag/v0.7.2
